import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MatDialog, MatDialogModule } from '@angular/material/dialog';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatTabsModule } from '@angular/material/tabs';
import { MatMenuModule } from '@angular/material/menu';
import { MatTooltipModule } from '@angular/material/tooltip';
import { Router } from '@angular/router';
import { AuthService } from '../../services/auth.service';
import { TenantContextService } from '../../services/tenant-context.service';
import { UniversalSidebarComponent, SidebarItem } from '../../shared/components/universal-sidebar.component';
import { StatsCardsComponent, StatCard } from '../../shared/components/stats-cards.component';
import { DataTableComponent, ColumnConfig } from '../../shared/components/data-table.component';
import { DateFilterComponent, DateFilter } from '../../shared/components/date-filter.component';
import { EmptyStateComponent } from '../../shared/components/empty-state.component';
import { LogoutModalComponent } from '../../shared/components/logout-modal.component';
import { PrintService } from '../../shared/services/print.service';

interface AdminReport {
  id: number;
  reportName: string;
  generatedBy: string;
  generatedDate: Date;
  status: string;
  recordCount: number;
}

@Component({
  selector: 'app-admin-dashboard',
  standalone: true,
  imports: [
    CommonModule,
    MatButtonModule,
    MatIconModule,
    MatDialogModule,
    MatTabsModule,
    MatMenuModule,
    MatTooltipModule,
    UniversalSidebarComponent,
    StatsCardsComponent,
    DataTableComponent,
    DateFilterComponent,
    EmptyStateComponent
  ],
  templateUrl: './admin-dashboard.component.html',
  styleUrl: './admin-dashboard.component.scss'
})
export class AdminDashboardComponent implements OnInit {
  // Admin Dashboard - Gray Theme
  private readonly ADMIN_COLOR = '#607d8b'; // Blue Gray
  
  sidebarItems: SidebarItem[] = [
    { icon: 'dashboard', label: 'Overview', action: 'overview', color: this.ADMIN_COLOR },
    { icon: 'people', label: 'User Management', action: 'users', color: '#546e7a' },
    { icon: 'assessment', label: 'Reports', action: 'reports', color: '#455a64' },
    { icon: 'security', label: 'Roles & Permissions', action: 'roles', color: '#37474f' },
    { icon: 'settings', label: 'System Settings', action: 'settings', color: '#263238' },
    { icon: 'history', label: 'Audit Logs', action: 'audit', color: '#78909c' }
  ];

  statCards: StatCard[] = [
    { title: 'Total Users', value: 245, icon: 'people', color: this.ADMIN_COLOR, trend: 12 },
    { title: 'Active Sessions', value: 78, icon: 'computer', color: '#546e7a', trend: -5 },
    { title: 'System Modules', value: 12, icon: 'apps', color: '#455a64', subtitle: 'All operational' },
    { title: 'Audit Events', value: '1.2K', icon: 'event_note', color: '#78909c', trend: 8 }
  ];

  tableColumns: ColumnConfig[] = [
    { key: 'reportName', label: 'Report Name', sortable: true },
    { key: 'generatedBy', label: 'Generated By', sortable: true },
    { key: 'generatedDate', label: 'Date', sortable: true, format: (val) => new Date(val).toLocaleDateString() },
    { key: 'status', label: 'Status', sortable: true },
    { key: 'recordCount', label: 'Records', sortable: true }
  ];

  reportsData: AdminReport[] = [
    { id: 1, reportName: 'User Activity Report', generatedBy: 'Admin', generatedDate: new Date(), status: 'Completed', recordCount: 450 },
    { id: 2, reportName: 'System Performance', generatedBy: 'System', generatedDate: new Date(), status: 'Completed', recordCount: 1200 },
    { id: 3, reportName: 'Security Audit', generatedBy: 'Admin', generatedDate: new Date(), status: 'Processing', recordCount: 0 }
  ];

  activeView: string = 'overview';
  filteredData: AdminReport[] = [];
  currentFilter: DateFilter = { startDate: null, endDate: null };

  constructor(
    private authService: AuthService,
    private tenantContext: TenantContextService,
    private dialog: MatDialog,
    private router: Router,
    private printService: PrintService
  ) {}

  ngOnInit(): void {
    this.filteredData = [...this.reportsData];
  }

  get currentUser() {
    return this.authService.currentUserValue;
  }

  get organisationName() {
    return this.tenantContext.getOrganisationName();
  }

  onSidebarItemClick(item: SidebarItem): void {
    if (item.action) {
      this.activeView = item.action;
    }
  }

  onLogout(): void {
    const dialogRef = this.dialog.open(LogoutModalComponent, {
      width: '400px',
      disableClose: true
    });

    dialogRef.afterClosed().subscribe(result => {
      if (result) {
        this.authService.logout();
        this.router.navigate(['/login']);
      }
    });
  }

  onFilterChange(filter: DateFilter): void {
    this.currentFilter = filter;
    this.applyDateFilter();
  }

  applyDateFilter(): void {
    if (!this.currentFilter.startDate || !this.currentFilter.endDate) {
      this.filteredData = [...this.reportsData];
      return;
    }

    this.filteredData = this.reportsData.filter(report => {
      const reportDate = new Date(report.generatedDate);
      return reportDate >= this.currentFilter.startDate! && reportDate <= this.currentFilter.endDate!;
    });
  }

  printReport(reportType: string): void {
    let reportData: any;
    let title: string;

    switch (reportType) {
      case 'userActivity':
        reportData = this.generateUserActivityReport();
        title = 'User Activity Report';
        break;
      case 'systemPerformance':
        reportData = this.generateSystemPerformanceReport();
        title = 'System Performance Report';
        break;
      case 'securityAudit':
        reportData = this.generateSecurityAuditReport();
        title = 'Security Audit Report';
        break;
      case 'rolePermissions':
        reportData = this.generateRolePermissionsReport();
        title = 'Roles & Permissions Report';
        break;
      case 'moduleUsage':
        reportData = this.generateModuleUsageReport();
        title = 'Module Usage Report';
        break;
      case 'systemHealth':
        reportData = this.generateSystemHealthReport();
        title = 'System Health Report';
        break;
      default:
        return;
    }

    this.printService.printReport(reportData, 'detailed', title);
  }

  exportToCSV(reportType: string): void {
    const data = this.filteredData;
    this.printService.exportToCSV(data, `admin_${reportType}_report`);
  }

  // Report Generation Methods
  private generateUserActivityReport(): any {
    return {
      summary: {
        totalUsers: 245,
        activeToday: 78,
        newThisMonth: 23,
        averageSessionTime: '45 mins'
      },
      items: this.reportsData
    };
  }

  private generateSystemPerformanceReport(): any {
    return {
      summary: {
        uptime: '99.9%',
        averageResponseTime: '120ms',
        totalRequests: '1.2M',
        errorRate: '0.01%'
      },
      items: []
    };
  }

  private generateSecurityAuditReport(): any {
    return {
      summary: {
        loginAttempts: 3240,
        failedLogins: 12,
        suspiciousActivity: 2,
        blockedIPs: 5
      },
      items: []
    };
  }

  private generateRolePermissionsReport(): any {
    return {
      summary: {
        totalRoles: 8,
        totalPermissions: 45,
        customRoles: 3,
        systemRoles: 5
      },
      items: []
    };
  }

  private generateModuleUsageReport(): any {
    return {
      summary: {
        totalModules: 12,
        activeModules: 12,
        mostUsed: 'Retail Sales',
        leastUsed: 'HR Management'
      },
      items: []
    };
  }

  private generateSystemHealthReport(): any {
    return {
      summary: {
        cpuUsage: '45%',
        memoryUsage: '62%',
        diskSpace: '78% used',
        databaseSize: '2.4 GB'
      },
      items: []
    };
  }

  addUser(): void {
    // Navigate to user management or open dialog
    this.activeView = 'users';
  }

  generateReport(): void {
    // Navigate to reports or open dialog
    this.activeView = 'reports';
  }

  viewSettings(): void {
    // Navigate to settings
    this.activeView = 'settings';
  }
}
